config/routes.rb
SampleApp::Application.routes.draw do   
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :teams
  resources :fixtures
  resources :scorelines
  resources :selections
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
      
  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
      
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/models/fixture.rb
class Fixture < ActiveRecord::Base
  attr_accessible :away_score, :away_team, :home_score, :home_team, :matchdate, :winner
end

app/controllers/fixtures_controller.rb
class FixturesController < ApplicationController
  # GET /fixtures
  # GET /fixtures.json
  def index
    @fixtures = Fixture.paginate(page: params[:page])
  end

  # GET /fixtures/1
  # GET /fixtures/1.json
  def show
    @fixture = Fixture.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fixture }
    end
  end

  # GET /fixtures/new
  # GET /fixtures/new.json
  def new
    @fixture = Fixture.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fixture }
    end
  end

  # GET /fixtures/1/edit
  def edit
    @fixture = Fixture.find(params[:id])
  end

  # POST /fixtures
  # POST /fixtures.json
  def create
    @fixture = Fixture.new(params[:fixture])

    respond_to do |format|
      if @fixture.save
        format.html { redirect_to @fixture, notice: 'Fixture was successfully created.' }
        format.json { render json: @fixture, status: :created, location: @fixture }
      else
        format.html { render action: "new" }
        format.json { render json: @fixture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fixtures/1
  # PUT /fixtures/1.json
  def update
    @fixture = Fixture.find(params[:id])

    respond_to do |format|
      if @fixture.update_attributes(params[:fixture])
        format.html { redirect_to @fixture, notice: 'Fixture was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @fixture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fixtures/1
  # DELETE /fixtures/1.json
  def destroy
    @fixture = Fixture.find(params[:id])
    @fixture.destroy

    respond_to do |format|
      format.html { redirect_to fixtures_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/fixtures_helper.rb
module FixturesHelper
end

app/views/fixtures/_fixture.html.erb
<li>
  <%= fixture.matchdate %>
  <%= fixture.home_team %>
  Vs 
  <%= fixture.away_team %>
  <% if current_user.admin? %>
    | <%= link_to 'Edit', edit_fixture_path(fixture) %>
	| <%= link_to "delete", fixture, method: :delete, confirm: "You sure?" %>
  <% end %>
</li>

app/views/fixtures/_form.html.erb
<%= form_for(@fixture) do |f| %>
  <% if @fixture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fixture.errors.count, "error") %> prohibited this fixture from being saved:</h2>

      <ul>
      <% @fixture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :matchdate %><br />
    <%= f.date_select :matchdate %>
  </div>
  <div class="field">
    <%= f.label :home_team %><br />
    <%= f.text_field :home_team %>
  </div>
  <div class="field">
    <%= f.label :away_team %><br />
    <%= f.text_field :away_team %>
  </div>
  <div class="field">
    <%= f.label :home_score %><br />
    <%= f.number_field :home_score %>
  </div>
  <div class="field">
    <%= f.label :away_score %><br />
    <%= f.number_field :away_score %>
  </div>
  <div class="field">
    <%= f.label :winner %><br />
    <%= f.text_field :winner %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fixtures/edit.html.erb
<h1>Editing fixture</h1>

<%= render 'form' %>

<%= link_to 'Show', @fixture %> |
<%= link_to 'Back', fixtures_path %>

app/views/fixtures/index.html.erb
<%= provide(:title, 'Fixture List') %>
<h1>Fixture List</h1>

<%= will_paginate %>

<ul class="fixtures">
  <%= render @fixtures %>
</ul>

<%= will_paginate %>

<%= link_to 'New Fixture', new_fixture_path %>

app/views/fixtures/new.html.erb
<h1>New fixture</h1>

<%= render 'form' %>

<%= link_to 'Back', fixtures_path %>

app/views/fixtures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Matchdate:</b>
  <%= @fixture.matchdate %>
</p>

<p>
  <b>Home team:</b>
  <%= @fixture.home_team %>
</p>

<p>
  <b>Away team:</b>
  <%= @fixture.away_team %>
</p>

<p>
  <b>Home score:</b>
  <%= @fixture.home_score %>
</p>

<p>
  <b>Away score:</b>
  <%= @fixture.away_score %>
</p>

<p>
  <b>Winner:</b>
  <%= @fixture.winner %>
</p>


<%= link_to 'Edit', edit_fixture_path(@fixture) %> |
<%= link_to 'Back', fixtures_path %>