config/routes.rb
SampleApp::Application.routes.draw do   
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :teams
  resources :fixtures
  resources :scorelines
  resources :selections
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
      
  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
      
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/models/selection.rb
class Selection < ActiveRecord::Base
  attr_accessible :match1, :match2, :match3, :match4, :match5, :match6, :match7, :match8, :user_id
end

app/controllers/selections_controller.rb
class SelectionsController < ApplicationController
  # GET /selections
  # GET /selections.json
  def index
    @selections = Selection.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @selections }
    end
  end

  # GET /selections/1
  # GET /selections/1.json
  def show
    @selection = Selection.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @selection }
    end
  end

  # GET /selections/new
  # GET /selections/new.json
  def new
    @selection = Selection.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @selection }
    end
  end

  # GET /selections/1/edit
  def edit
    @selection = Selection.find(params[:id])
  end

  # POST /selections
  # POST /selections.json
  def create
    @selection = Selection.new(params[:selection])

    respond_to do |format|
      if @selection.save
        format.html { redirect_to @selection, notice: 'Selection was successfully created.' }
        format.json { render json: @selection, status: :created, location: @selection }
      else
        format.html { render action: "new" }
        format.json { render json: @selection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /selections/1
  # PUT /selections/1.json
  def update
    @selection = Selection.find(params[:id])

    respond_to do |format|
      if @selection.update_attributes(params[:selection])
        format.html { redirect_to @selection, notice: 'Selection was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @selection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /selections/1
  # DELETE /selections/1.json
  def destroy
    @selection = Selection.find(params[:id])
    @selection.destroy

    respond_to do |format|
      format.html { redirect_to selections_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/selections_helper.rb
module SelectionsHelper
end

app/views/selections/_form.html.erb
<%= form_for(@selection) do |f| %>
  <% if @selection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@selection.errors.count, "error") %> prohibited this selection from being saved:</h2>

      <ul>
      <% @selection.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :match1 %><br />
    <%= f.number_field :match1 %>
  </div>
  <div class="field">
    <%= f.label :match2 %><br />
    <%= f.number_field :match2 %>
  </div>
  <div class="field">
    <%= f.label :match3 %><br />
    <%= f.number_field :match3 %>
  </div>
  <div class="field">
    <%= f.label :match4 %><br />
    <%= f.number_field :match4 %>
  </div>
  <div class="field">
    <%= f.label :match5 %><br />
    <%= f.number_field :match5 %>
  </div>
  <div class="field">
    <%= f.label :match6 %><br />
    <%= f.number_field :match6 %>
  </div>
  <div class="field">
    <%= f.label :match7 %><br />
    <%= f.number_field :match7 %>
  </div>
  <div class="field">
    <%= f.label :match8 %><br />
    <%= f.number_field :match8 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/selections/edit.html.erb
<h1>Editing selection</h1>

<%= render 'form' %>

<%= link_to 'Show', @selection %> |
<%= link_to 'Back', selections_path %>

app/views/selections/index.html.erb
<h1>Listing selections</h1>

<table>
  <tr>
    <th>User</th>
    <th>Match1</th>
    <th>Match2</th>
    <th>Match3</th>
    <th>Match4</th>
    <th>Match5</th>
    <th>Match6</th>
    <th>Match7</th>
    <th>Match8</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @selections.each do |selection| %>
  <tr>
    <td><%= selection.user_id %></td>
    <td><%= selection.match1 %></td>
    <td><%= selection.match2 %></td>
    <td><%= selection.match3 %></td>
    <td><%= selection.match4 %></td>
    <td><%= selection.match5 %></td>
    <td><%= selection.match6 %></td>
    <td><%= selection.match7 %></td>
    <td><%= selection.match8 %></td>
    <td><%= link_to 'Show', selection %></td>
    <td><%= link_to 'Edit', edit_selection_path(selection) %></td>
    <td><%= link_to 'Destroy', selection, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Selection', new_selection_path %>

app/views/selections/new.html.erb
<h1>New selection</h1>

<%= render 'form' %>

<%= link_to 'Back', selections_path %>

app/views/selections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @selection.user_id %>
</p>

<p>
  <b>Match1:</b>
  <%= @selection.match1 %>
</p>

<p>
  <b>Match2:</b>
  <%= @selection.match2 %>
</p>

<p>
  <b>Match3:</b>
  <%= @selection.match3 %>
</p>

<p>
  <b>Match4:</b>
  <%= @selection.match4 %>
</p>

<p>
  <b>Match5:</b>
  <%= @selection.match5 %>
</p>

<p>
  <b>Match6:</b>
  <%= @selection.match6 %>
</p>

<p>
  <b>Match7:</b>
  <%= @selection.match7 %>
</p>

<p>
  <b>Match8:</b>
  <%= @selection.match8 %>
</p>


<%= link_to 'Edit', edit_selection_path(@selection) %> |
<%= link_to 'Back', selections_path %>